AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TryKinesisLambda

Globals:
  Function:
    Timeout: 10


Resources:

  TestStream:
    Type: AWS::Kinesis::Stream
    Properties:
        Name: test-stream
        ShardCount: 1

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        HelloWorldStream:
          # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#kinesis
          Type: Kinesis
          Properties:
            Stream: !GetAtt TestStream.Arn
            StartingPosition: LATEST
            BatchSize: 3
