AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TryKinesisLambda

Globals:
  Function:
    Timeout: 3


Resources:

  TestStream:
    Type: AWS::Kinesis::Stream
    Properties:
        Name: test-stream
        ShardCount: 1

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
